# Generated by Django 3.2.5 on 2021-08-03 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('RF', 'Recieved from'), ('IT', 'Issued to')], default='RF', max_length=20)),
                ('material_name', models.CharField(choices=[('key board', 'key board'), ('mouse', 'mouse'), ('phone', 'phone'), ('labtop', 'laptop')], default='phone', max_length=100)),
                ('date', models.DateField()),
                ('doc_no', models.IntegerField(unique=True)),
                ('received_from', models.CharField(blank=True, max_length=200, null=True)),
                ('receipt_no', models.IntegerField()),
                ('issue', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.IntegerField()),
                ('verification_date', models.DateField()),
                ('verified_by', models.CharField(max_length=100)),
            ],
        ),
    ]
